### ISSUE TITLE
Issue on new versions...

### ISSUE THREAD

**Issue by platini76** [gawindx/homebridge-risco-platform#31] opened 2020-12-03 20:19 UTC
[3/12/2020, 21:19:01] [RiscoAlarm] Create Accessory Phase Started
(node:25885) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Timeout'
    |     property '_idlePrev' -> object with constructor 'TimersList'
    --- property '_idleNext' closes the circle
    at JSON.stringify (<anonymous>)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-risco-platform/app.js:115:53)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:25885) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:25885) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[3/12/2020, 21:19:02] [RiscoAlarm] Restoring or Set Removing accessory Partizione 1
[3/12/2020, 21:19:02] TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Timeout'
    |     property '_idlePrev' -> object with constructor 'TimersList'
    --- property '_idleNext' closes the circle
    at JSON.stringify (<anonymous>)
    at /usr/lib/node_modules/homebridge-risco-platform/app.js:156:70
    at Array.map (<anonymous>)
    at RiscoPanelPlatform.configureAccessory (/usr/lib/node_modules/homebridge-risco-platform/app.js:155:18)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[3/12/2020, 21:19:02] [RiscoAlarm] Restoring or Set Removing accessory Partizione 2
[3/12/2020, 21:19:02] TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Timeout'
    |     property '_idlePrev' -> object with constructor 'TimersList'
    --- property '_idleNext' closes the circle
    at JSON.stringify (<anonymous>)
    at /usr/lib/node_modules/homebridge-risco-platform/app.js:156:70
    at Array.map (<anonymous>)
    at RiscoPanelPlatform.configureAccessory (/usr/lib/node_modules/homebridge-risco-platform/app.js:155:18)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

**Comment by gawindx** [comment] 2020-12-03 21:00
rather surprising.

can you give me more information about your configuration:
- homebridge version
- npm and node js version
- your config file (without sensitive information)
- any special characters in device names?
- how is your homebridge hosted (docker? hoobs? mac ?, etc ...)

Can you also tell me if you already have accessories in the cache or if it is a new config?

**Comment by platini76** [comment] 2020-12-03 21:43
yes sure!

homebridge version  1.23
npm and node js version  14.5.1  / 6.14.9
your config file (without sensitive information)  

{
            "platform": "RiscoAlarm",
            "name": "RiscoAlarm",
            "riscoPIN": "1111",
            "pollInterval": 15000,
            "polling": true,
            "riscoUsername": "XXXXXXX",
            "riscoPassword": "XXXXXXX",
            "riscoSiteId": XXXX,
            "Partition_Mode": "true",
            "Partition": "all"
        },
any special characters in device names?  not changed in last 4 years... no, no special char
how is your homebridge hosted (docker? hoobs? mac ?, etc ...)  linux mint 19.3
thanks
davide

**Comment by platini76** [comment] 2020-12-04 00:00
[4/12/2020, 00:59:21] [RiscoAlarm] RiscoPanelPlatform Initial Discovery Phase
(node:903) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 didFinishLaunching listeners added to [HomebridgeAPI]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)

I have also this

**Comment by platini76** [comment] 2020-12-04 01:19
and also this.... 

[4/12/2020, 02:18:35] [RiscoAlarm] PreConf Phase Started
[4/12/2020, 02:18:35] [RiscoAlarm] PreConf Accessory => Add Partitions
[4/12/2020, 02:18:35] [RiscoAlarm] PreConf Accessory => Configuration for Partitions Id : 0 and labeled "Partizione 1"
[4/12/2020, 02:18:35] [RiscoAlarm] PreConf Accessory => Configuration for Partitions Id : 1 and labeled "Partizione 2"
[4/12/2020, 02:18:35] [RiscoAlarm] PreConf Phase Ended
[4/12/2020, 02:18:35] [RiscoAlarm] Create Accessory Phase Started
(node:4817) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Timeout'
    |     property '_idlePrev' -> object with constructor 'TimersList'
    --- property '_idleNext' closes the circle
    at JSON.stringify (<anonymous>)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-risco-platform/app.js:115:53)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:4817) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4817) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by platini76** [comment] 2020-12-04 13:34
any solution? I have all my house down.. ad homebridge continue reboot

**Comment by gawindx** [comment] 2020-12-04 17:21
not at the moment, and for several reasons:
- you are for the moment the only one to tell me this problem and I can not reproduce it.
- the lines of code posing problems have not been modified on the last versions
- the "circular structure" error occurs in the case where we try to "serialize" an object in which we refer to this same object, which is absolutely not the case in this plugin (otherwise you do not would not be the only one and I would have realized it well before publishing this version)
- the last being the most important, I develop this project in my free time and therefore when I am not working which means evenings and weekends while keeping some free time to spend with my loved ones.

I am sincerely sorry for the problems that you encounter and I do my best to find a solution but if this is too problematic, it is possible to downgrade the version via the plugin tab in the homebridge web interface (but be careful in if the network is cut for too long, the plugin risks losing the connection to RiscoCloud and will not find it on its own, unlike the last version).

As you are on a linux mint, I think you are able to work directly on the plugin files, so I will provide you (Saturday or Sunday) with a modified version of the "app.js" file to test and see if you still have the same problem.

On the other hand, since the portion of the code which poses problem has not changed since several versions, I will tend to think that the problem is caused by a specificity of your linux, but this deduction is only my opinion.

**Comment by platini76** [comment] 2020-12-04 17:32
hello, thanks for write me and for explanations: yes I tried to downgrade and it works for some days... now I have the problem you said: the plugin risks losing the connection to RiscoCloud and will not find it on its own, unlike the last version

thanks really for all! I can also give you my ssh...if it help you!

**Comment by gawindx** [comment] 2020-12-04 17:41
a tip when the connection is lost: a simple command, whether arming / disarming, exclusion of a zone or an action on an output (or a combined accessory) will force the plugin to reconnect.

and for ssh I don't think this is necessary.
all you have to do is replace the content of the app.js file, in other words you just need to be able to edit the file (either via a nano but you will have to delete the content to replace it or via a gedit if you are with gnome, kate it seems to me for kde - after I do not particularly know mint so it's up to you)

**Comment by platini76** [comment] 2020-12-04 18:16
I have completely reinstalled linux mint 20

now i have this error:
[4/12/2020, 19:06:49] [RiscoAlarm] Cloud Authentication Successfull
[4/12/2020, 19:06:49] [RiscoAlarm] Retrieving Cloud Session: Ok
[4/12/2020, 19:06:50] [RiscoAlarm] Discovered 2 Partitions
[4/12/2020, 19:06:50] [RiscoAlarm] Discovering Phase Ended
[4/12/2020, 19:06:50] [RiscoAlarm] PreConf Phase Started
[4/12/2020, 19:06:50] [RiscoAlarm] PreConf Accessory => Add Partitions
[4/12/2020, 19:06:50] [RiscoAlarm] PreConf Accessory => Configuration for Partitions Id : 0 and labeled "Partizione 1"
[4/12/2020, 19:06:50] [RiscoAlarm] PreConf Accessory => Configuration for Partitions Id : 1 and labeled "Partizione 2"
[4/12/2020, 19:06:50] [RiscoAlarm] PreConf Phase Ended
[4/12/2020, 19:06:50] [RiscoAlarm] Create Accessory Phase Started
[4/12/2020, 19:06:50] [RiscoAlarm] Adding new accessory with Name: Partizione 1, Id: 0, type: Partitions
[4/12/2020, 19:06:50] [RiscoAlarm] Error on Create Accessory Phase :
%sTypeError: Cannot read property 'getCharacteristic' of undefined
[4/12/2020, 19:06:50] [RiscoAlarm] Accessories Init Phase Ended

**Comment by gawindx** [comment] 2020-12-04 18:58
ok, so the previous problem must have come from your linux.

It doesn't totally solve your worries but it does get things done.

The problem you are having now is the same as for issue # 30; and you answer at the same time to one of my questions namely, does this problem also appear by deleting the accessories cache and apparently this is the case.

Can you try to comment out lines 207 to 212 in the app.js file and tell me if it works or if a new error appears:

/*
if ((accessory.getService(Service.AccessoryInformation).getCharacteristic(Characteristic.SerialNumber).value) != pjson.version) {
            //do some stuff on update accessory from older version of plugin
            accessory.getService(Service.AccessoryInformation)
                .setCharacteristic(Characteristic.SerialNumber, pjson.version)
                .setCharacteristic(Characteristic.FirmwareRevision, pjson.version);
        }
*/

**Comment by platini76** [comment] 2020-12-04 19:09
sorry can you give me the locatio of this file?

**Comment by gawindx** [comment] 2020-12-04 19:59
if your re-installation of mint is done the same way as the previous one, it should be there:

/usr/lib/node_modules/homebridge-risco-platform/app.js

**Comment by platini76** [comment] 2020-12-04 20:44
.setCharacteristic(Characteristic.FirmwareRevision, pjson.version);

        }
/*
        if ((accessory.getService(Service.AccessoryInformation).getCharacteristic(Characteristic.SerialNumber).value) != pjson.version) {
            //do some stuff on update accessory from older version of plugin
            accessory.getService(Service.AccessoryInformation)
                .setCharacteristic(Characteristic.SerialNumber, pjson.version)
                .setCharacteristic(Characteristic.FirmwareRevision, pjson.version);
        }
*/
        switch (type) {
            case 'System':
            case 'Partitions':
                if (add) {



this is partially my file, it was diffocult to change (cannot be removed ... but I used nano)

no results... still the same.

[4/12/2020, 21:41:50] [RiscoAlarm] Cloud Authentication Successfull
[4/12/2020, 21:41:50] [RiscoAlarm] Retrieving Cloud Session: Ok
[4/12/2020, 21:41:51] [RiscoAlarm] Discovered 2 Partitions
[4/12/2020, 21:41:51] [RiscoAlarm] Discovering Phase Ended
[4/12/2020, 21:41:51] [RiscoAlarm] PreConf Phase Started
[4/12/2020, 21:41:51] [RiscoAlarm] PreConf Accessory => Add Partitions
[4/12/2020, 21:41:51] [RiscoAlarm] PreConf Accessory => Configuration for Partitions Id : 0 and labeled "Partizione 1"
[4/12/2020, 21:41:51] [RiscoAlarm] PreConf Accessory => Configuration for Partitions Id : 1 and labeled "Partizione 2"
[4/12/2020, 21:41:51] [RiscoAlarm] PreConf Phase Ended
[4/12/2020, 21:41:51] [RiscoAlarm] Create Accessory Phase Started
[4/12/2020, 21:41:51] [RiscoAlarm] Adding new accessory with Name: Partizione 1, Id: 0, type: Partitions
[4/12/2020, 21:41:51] [RiscoAlarm] Error on Create Accessory Phase :
%sTypeError: Cannot read property 'getCharacteristic' of undefined
[4/12/2020, 21:41:51] [RiscoAlarm] Accessories Init Phase Ended

**Comment by gawindx** [comment] 2020-12-04 21:16
interesting.

reverts to a previous version for now.

I will prepare a file which will give a little more info but it will take a little while.

on the old version, the connection will remain active as long as there is no network cut.

by the way, if you can give me the latest version that didn't give you the getchatacteristic error, that will allow me to see what changes I've made since then, and maybe understand what's going on.

**Comment by platini76** [comment] 2020-12-04 21:22
2 weeks ago I saw a problem on plugin, I reinstalled the previuos version and seems to go better, but since 2.2 version was released I can't go down anymore because now I had many errors.. now I will make some testes with previuos versions.

**Comment by platini76** [comment] 2020-12-04 21:48
sorry I had not uograded hmebridge that was at 1.16
now with 1.23 log is this one:

[4/12/2020, 22:47:25] [RiscoAlarm] Cloud Authentication Successfull
[4/12/2020, 22:47:25] [RiscoAlarm] Retrieving Cloud Session: Ok
[4/12/2020, 22:47:25] [RiscoAlarm] Discovered 2 Partitions
[4/12/2020, 22:47:25] [RiscoAlarm] Discovering Phase Ended
[4/12/2020, 22:47:25] [RiscoAlarm] PreConf Phase Started
[4/12/2020, 22:47:25] [RiscoAlarm] PreConf Accessory => Add Partitions
[4/12/2020, 22:47:25] [RiscoAlarm] PreConf Accessory => Configuration for Partitions Id : 0 and labeled "Partizione 1"
[4/12/2020, 22:47:25] [RiscoAlarm] PreConf Accessory => Configuration for Partitions Id : 1 and labeled "Partizione 2"
[4/12/2020, 22:47:25] [RiscoAlarm] PreConf Phase Ended
[4/12/2020, 22:47:25] [RiscoAlarm] Create Accessory Phase Started
(node:5224) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Timeout'
    |     property '_idlePrev' -> object with constructor 'TimersList'
    --- property '_idleNext' closes the circle
    at JSON.stringify (<anonymous>)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-risco-platform/app.js:115:53)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5224) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:5224) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by gawindx** [comment] 2020-12-06 18:27
I finally figured out how to reproduce the problem.
Version 1.2.3 must fix this

**Comment by platini76** [comment] 2020-12-06 18:29
really??? what was???

**Comment by gawindx** [comment] 2020-12-06 18:58
On the last versions, I reintroduced the corrected occupancy function which was previously not very stable.
I took the opportunity to change the name of certain variable to make them clearer and ... I forgot to change one.
The consequence was that the occupancy sensor was removed from the accessory when the conditions for it to be managed correctly were not present (parameters configured to false in the config file, no detector configured, only groups, etc. ) but, as the conditions were correctly met in the class of the accessory itself, the accessory sought to assign the functions linked to the sensor which, for the moment, no longer existed in the accessory.

So, no problem in some cases but in others, it stuck.

**Comment by platini76** [comment] 2020-12-06 19:00
thanks very very much guy... can I ask a question on my config? here I think it is not a place for it.

**Comment by gawindx** [comment] 2020-12-06 19:03
go ahead and if it's too complex we'll open a specific issue

**Comment by platini76** [comment] 2020-12-06 19:15
so my config is:
{
    "platform": "RiscoAlarm",
    "name": "RiscoAlarm",
    "riscoPIN": "XXXX",
    "pollInterval": 15000,
    "polling": true,
    "riscoUsername": "XXXXXXX",
    "riscoPassword": "XXXXXX",
    "riscoSiteId": XXXX,
    "Partition_Mode": "true",
    "Partition": "all"
}

in my risco I have two partitions:
one for perimeter (partizione1) and one for inside (partizione2)
now I have two separate switches
I would like to have only one switch with 
in home: no alarm activated
out home: all partitions activated
night: activate partition 1
not active: no activation

what I have to config?

thanks!

**Comment by gawindx** [comment] 2020-12-06 19:41
My first opinion is that the basic configuration of the control unit is not the most optimized in your case.
Clearly, what you are describing is the operation of a single partition with a partial mode.
This means that in partial mode, only the zones defined in total are armed.
In Away mode, all zones are armed.

Now, to get the operation you want, you would have to define the system mode for the partitions in the config.json.
Then, you have to add the commands you want in the config file.
           "armCommand": "armed | partially | disarmed",
           "partialCommand": "armed | partially | disarmed",
           "homeCommand": "armed | partially | disarmed",
           "disarmCommand": "armed | partially | disarmed",

On the other hand, I think I am not mistaken in saying that I did not reflect on these options to arm a specific partition and not the others.
So there's a 9 out of 10 chance that it won't work.

But it can be changed.

**Comment by platini76** [comment] 2020-12-06 20:13
so it can be:

so my config is:
{
"platform": "RiscoAlarm",
"name": "RiscoAlarm",
"riscoPIN": "XXXX",
"pollInterval": 15000,
"polling": true,
"riscoUsername": "XXXXXXX",
"riscoPassword": "XXXXXX",
"riscoSiteId": XXXX,
"armCommand": "armed",
"partialCommand": "partition1",
"homeCommand": "disarmed",
"disarmCommand": "disarmed",
"Partition_Mode": "true",
"Partition": "all"
}


but it is no possible because partition1 is not an arm command.., right?

**Comment by gawindx** [comment] 2020-12-07 17:31
Not exactly.
The "Partition_Mode" parameter is obsolete and is no longer used (whether it is present or not does not change anything and has no effect).
The "Partition" parameter should either be absent (system mode by default only if no Group / Partition is configured) or have the value "system" (it is this parameter which replaces "Partition_Mode" configured to false, any other value equivalent to "Partition_Mode" = true).

And indeed, the partialCommand should look like a value in this style.
But currently I have not developed it in this direction so it will not work (and if I am not mistaken, since it does not correspond to an expected value, the value will not be taken into account).

**Comment by platini76** [comment] 2020-12-07 22:35
so you suggest to change configurantion on my risco system to:

perimeter zone = partial ?


or maybe I have not understand well... sorry but I am italian and a noob in configurations

**Comment by gawindx** [comment] 2020-12-10 16:23
It is a possibility, if you have the hand in programming on your system you can indeed modify the programming in this direction.

Being skilled in the art, it is common for the partial mode to be used when the installation includes perimetry.

For programming, on Risco central units, the partial is programmed as follows:
- Put all zones in the same partitions.
- No modification of zone types for zones which must be armed both fully and partially
- For zones which must be armed only in full operation and which are therefore not armed in partial operation, the type of zone corresponding to the 2 operating modes must be selected.
This type of zone is indicated "Int + XXXX" where XXXX corresponds to the operating mode of the zone in full operation, example:
A zone must be Immediate in Full marce but not partially armed, it must be assigned the type "Int + Immediate".
For a timed zone:
"Int + I / O 1" (1 or 2 depending on the tempo used)
and a delayed zone which can be opened during the delay:
"Int + I / O Open 1" (1 or 2 depending on the tempo used)
Etc ...
To simplify, you take the current zone type and assign it the corresponding zone type in partial, ie "Int + Current Type"

But if you give me a few weeks (I have another project that I will have to take a closer look at), I'll add the possibility of specifying a score to custom commands.

**Comment by platini76** [comment] 2020-12-12 03:56
Hello,
ok I now have partial that arm only my perimeter and one partition only.
I have a question, if I want to arm only internal zones and not perimeter is impossible?
or I can make groups?
thanks
davide

**Comment by andyblac** [comment] 2020-12-13 14:06
@gawindx why is this 28000 sec delay to arm. ???

```
[13/12/2020, 01:57:15] [RiscoAlarm] The partition will be armed in 28000 milliseconds
[13/12/2020, 01:57:50] [RiscoAlarm] Partition "Castle Int Alarm" => New state detected: (1) -> AWAY_ARM. Notify!
[13/12/2020, 01:57:50] [RiscoAlarm] Partition "Castle Int Alarm" is not Occupied. Notify!
```

**Comment by andyblac** [comment] 2020-12-13 14:07
also geting this
```
[13/12/2020, 08:49:32] [RiscoAlarm] Error on armDisarm function:
Error: Bad HTTP Response: 200
    at RiscoPanelSession.armDisarm (/usr/local/lib/node_modules/homebridge-risco-platform/Risco.js:1220:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at RiscoCPPartitions.GetSetArmState (/usr/local/lib/node_modules/homebridge-risco-platform/RiscoAccessories.js:371:38)
    at RiscoCPPartitions.setTargetState (/usr/local/lib/node_modules/homebridge-risco-platform/RiscoAccessories.js:272:47)
[13/12/2020, 08:49:33] [RiscoAlarm] Retrieving Cloud Session: Ok
```

**Comment by gawindx** [comment] 2020-12-14 17:59
It seems that the connection was no longer active or that the arming command arrived at the same time as the end of the validity of the session.

Either it's a stroke of luck, or you don't have the latest version of the plugin (Please note, I modified the Homebridge version prerequisites on the latest version of the plugin, so it is possible that your Homebridge version does not match not, which will explain why you encountered this problem).

Regarding the 28 second delay, this information normally only appears when the delayed arming / disarming is activated for the Cloud settings of your control panel.

If this is the case, this is normal operation of the plugin and the 28 second tempo corresponds to the remaining arming tempo (~~and it must update at each polling until the system is armed~~ - Since switching to the iRisco API, the tempo no longer updates with each polling).
If this is not the case, this info does not have to be and it is a bug on the RiscoCloud side because I get this info from the responses of the API, it is not me who generates it in the code.

**Comment by andyblac** [comment] 2020-12-14 18:09
I can arm in the app with no delay ? why is it delay your plugin ?

**Comment by andyblac** [comment] 2020-12-14 18:10
or do you mean it is the panel count down ?, if so it is just a new info from cloud?

**Comment by gawindx** [comment] 2020-12-14 19:46
it seems to me that by default, the arming from iRisco is not timed.
Activating the time delay for the web (whether from the web interface or the iRisco application) is done by activating an option in the control panel settings.

This information was already reported by the cloud, and I used it from the first versions of the plugin.
Maybe you've never noticed it.

This delay does indeed correspond to the exit countdown and, logically, I have no other choice but to take this tempo into account because if I report the accessory as armed while the countdown does not is not finished, I will then indicate an incorrect state.
The main risk being an arming failure when Homekit could indicate that everything is OK.

And it is indeed possible to deactivate this option in programming to obtain immediate arming of the partition (s). You just need to have access to the programming menu of your system or via ConfigurationSoftware.

this modification will have no impact on the local arming, whether from a keypad or a remote control.

**Comment by platini76** [comment] 2020-12-20 01:04
> Hello,
> ok I now have partial that arm only my perimeter and one partition only.
> I have a question, if I want to arm only internal zones and not perimeter is impossible?
> or I can make groups?
> thanks
> davide

**Comment by gawindx** [comment] 2020-12-21 21:50
sorry, I think I have not seen him pass.

so, yes, you can use a group but be careful ... you can arm the group alone but you cannot disarm it.
The disarming of a group necessarily involves the disarming of all the partitions to which it belongs.
This action is transparent and is automatically performed by the plugin so no complicated actions for a director.
But it is better to know it beforehand because it obliges to, if necessary, re-arm certain partitions (and that, it remains a manual action).

**Closed as completed** 2021-03-20 17:45 UTC
